//
//  StudyPackExporter.swift
//  MuseDrop
//
//  Turns a generated study pack (MediaAnalysis) into a shareable Markdown
//  document and presents the macOS share sheet (Mail / AirDrop / Messages / …)
//  or a save panel for downloading the file to disk.
//

import Foundation
import AppKit
import UniformTypeIdentifiers

enum StudyPackExporter {

    // MARK: - Markdown rendering

    /// Render the full study pack to a single Markdown document.
    static func markdown(for analysis: MediaAnalysis) -> String {
        var out = ""
        let title = analysis.mediaTitle.trimmingCharacters(in: .whitespacesAndNewlines)
        out += "# \(title.isEmpty ? "Study Pack" : title)\n\n"
        out += "_Generated by Kekasatori_\n\n"

        // Summary
        let summary = analysis.summary
        if !summary.oneLine.isEmpty || !summary.paragraph.isEmpty || !summary.bullets.isEmpty {
            out += "## Summary\n\n"
            if !summary.oneLine.isEmpty { out += "**\(summary.oneLine)**\n\n" }
            if !summary.paragraph.isEmpty { out += "\(summary.paragraph)\n\n" }
            for bullet in summary.bullets where !bullet.isEmpty {
                out += "- \(bullet)\n"
            }
            if !summary.bullets.isEmpty { out += "\n" }
        }

        // Notes
        let notes = analysis.notes
        if !notes.sections.isEmpty {
            out += "## Notes\n\n"
            for section in notes.sections {
                if !section.heading.isEmpty { out += "### \(section.heading)\n\n" }
                if !section.content.isEmpty { out += "\(section.content)\n\n" }
                for bullet in section.bullets where !bullet.isEmpty {
                    out += "- \(bullet)\n"
                }
                if !section.bullets.isEmpty { out += "\n" }
            }
        }

        // Key concepts
        if !analysis.keyConcepts.isEmpty {
            out += "## Key Concepts\n\n"
            for concept in analysis.keyConcepts {
                out += "- **\(concept.term)** — \(concept.definition)\n"
            }
            out += "\n"
        }

        // Flashcards
        if !analysis.flashcards.isEmpty {
            out += "## Flashcards\n\n"
            for (index, card) in analysis.flashcards.enumerated() {
                out += "\(index + 1). **Q:** \(card.front)\n"
                out += "   **A:** \(card.back)\n\n"
            }
        }

        // Mind map
        let mindMap = analysis.mindMap
        if !mindMap.nodes.isEmpty {
            out += "## Mind Map\n\n"
            if !mindMap.centralTopic.isEmpty { out += "**\(mindMap.centralTopic)**\n\n" }
            for node in mindMap.primaryNodes {
                out += "- \(node.label)\n"
                for child in mindMap.children(of: node.id) {
                    out += "  - \(child.label)\n"
                }
            }
            out += "\n"
        }

        // Transcript
        let transcript = analysis.transcript.text.trimmingCharacters(in: .whitespacesAndNewlines)
        if !transcript.isEmpty {
            out += "## Transcript\n\n"
            out += transcript
            out += "\n"
        }

        return out
    }

    /// Sanitized base filename (no extension) derived from the media title.
    static func fileBaseName(for analysis: MediaAnalysis) -> String {
        let raw = analysis.mediaTitle.trimmingCharacters(in: .whitespacesAndNewlines)
        let cleaned = raw.isEmpty ? "Study Pack" : raw
        let invalid = CharacterSet(charactersIn: "/\\?%*|\"<>:")
        let safe = cleaned.components(separatedBy: invalid).joined(separator: "-")
        return String(safe.prefix(80))
    }

    // MARK: - Share / Save

    /// Present the system share sheet for the study pack (Mail, AirDrop, …).
    /// Writes the Markdown to a temp file so recipients get a real attachment.
    @MainActor
    static func share(_ analysis: MediaAnalysis, from anchor: NSView? = nil) {
        guard let url = writeTempFile(for: analysis) else { return }
        let picker = NSSharingServicePicker(items: [url])
        let view = anchor ?? NSApp.keyWindow?.contentView
        if let view {
            picker.show(relativeTo: view.bounds, of: view, preferredEdge: .minY)
        }
    }

    /// Prompt the user to save the study pack Markdown file to disk.
    @MainActor
    static func saveToDevice(_ analysis: MediaAnalysis) {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [UTType(filenameExtension: "md") ?? .plainText]
        panel.nameFieldStringValue = "\(fileBaseName(for: analysis)).md"
        panel.canCreateDirectories = true
        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }
            do {
                try markdown(for: analysis).write(to: url, atomically: true, encoding: .utf8)
            } catch {
                LogService.shared.error("Study pack export failed", error: error)
                let alert = NSAlert()
                alert.messageText = "Couldn't save study pack"
                alert.informativeText = error.localizedDescription
                alert.alertStyle = .warning
                alert.runModal()
            }
        }
    }

    /// Write the Markdown to a uniquely-named temp file for sharing.
    private static func writeTempFile(for analysis: MediaAnalysis) -> URL? {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("StudyPackExports", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent("\(fileBaseName(for: analysis)).md")
        do {
            try markdown(for: analysis).write(to: url, atomically: true, encoding: .utf8)
            return url
        } catch {
            LogService.shared.error("Study pack share export failed", error: error)
            return nil
        }
    }
}
