//
//  StudyPackExporter.swift
//  MuseDrop
//
//  Turns a generated study pack (MediaAnalysis) into a shareable Markdown
//  document and presents the macOS share sheet (Mail / AirDrop / Messages / …)
//  or a save panel for downloading the file to disk.
//

import Foundation
import AppKit
import UniformTypeIdentifiers

enum StudyPackExporter {

    // MARK: - Markdown rendering

    /// Render the full study pack to a single Markdown document.
    static func markdown(for analysis: MediaAnalysis) -> String {
        var out = ""
        let title = analysis.mediaTitle.trimmingCharacters(in: .whitespacesAndNewlines)
        out += "# \(title.isEmpty ? "Study Pack" : title)\n\n"
        out += "_Generated by Kekasatori_\n\n"

        // Summary
        let summary = analysis.summary
        if !summary.oneLine.isEmpty || !summary.paragraph.isEmpty || !summary.bullets.isEmpty {
            out += "## Summary\n\n"
            if !summary.oneLine.isEmpty { out += "**\(summary.oneLine)**\n\n" }
            if !summary.paragraph.isEmpty { out += "\(summary.paragraph)\n\n" }
            for bullet in summary.bullets where !bullet.isEmpty {
                out += "- \(bullet)\n"
            }
            if !summary.bullets.isEmpty { out += "\n" }
        }

        // Notes
        let notes = analysis.notes
        if !notes.sections.isEmpty {
            out += "## Notes\n\n"
            for section in notes.sections {
                if !section.heading.isEmpty { out += "### \(section.heading)\n\n" }
                if !section.content.isEmpty { out += "\(section.content)\n\n" }
                for bullet in section.bullets where !bullet.isEmpty {
                    out += "- \(bullet)\n"
                }
                if !section.bullets.isEmpty { out += "\n" }
            }
        }

        // Key concepts
        if !analysis.keyConcepts.isEmpty {
            out += "## Key Concepts\n\n"
            for concept in analysis.keyConcepts {
                out += "- **\(concept.term)** — \(concept.definition)\n"
            }
            out += "\n"
        }

        // Flashcards
        if !analysis.flashcards.isEmpty {
            out += "## Flashcards\n\n"
            for (index, card) in analysis.flashcards.enumerated() {
                out += "\(index + 1). **Q:** \(card.front)\n"
                out += "   **A:** \(card.back)\n\n"
            }
        }

        // Mind map
        let mindMap = analysis.mindMap
        if !mindMap.nodes.isEmpty {
            out += "## Mind Map\n\n"
            if !mindMap.centralTopic.isEmpty { out += "**\(mindMap.centralTopic)**\n\n" }
            for node in mindMap.primaryNodes {
                out += "- \(node.label)\n"
                for child in mindMap.children(of: node.id) {
                    out += "  - \(child.label)\n"
                }
            }
            out += "\n"
        }

        // Transcript
        let transcript = analysis.transcript.text.trimmingCharacters(in: .whitespacesAndNewlines)
        if !transcript.isEmpty {
            out += "## Transcript\n\n"
            out += transcript
            out += "\n"
        }

        return out
    }

    /// Sanitized base filename (no extension) derived from the media title.
    static func fileBaseName(for analysis: MediaAnalysis) -> String {
        sanitizedBaseName(analysis.mediaTitle)
    }

    /// Strip characters illegal in filenames and clamp the length.
    static func sanitizedBaseName(_ raw: String) -> String {
        let cleaned = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        let name = cleaned.isEmpty ? "Study Pack" : cleaned
        let invalid = CharacterSet(charactersIn: "/\\?%*|\"<>:")
        let safe = name.components(separatedBy: invalid).joined(separator: "-")
        return String(safe.prefix(80))
    }

    // MARK: - Share / Save

    /// Present the system share sheet for the study pack (Mail, AirDrop, …).
    /// Writes the Markdown to a temp file so recipients get a real attachment.
    @MainActor
    static func share(_ analysis: MediaAnalysis, from anchor: NSView? = nil) {
        guard let url = writeTempFile(for: analysis) else { return }
        let picker = NSSharingServicePicker(items: [url])
        let view = anchor ?? NSApp.keyWindow?.contentView
        if let view {
            picker.show(relativeTo: view.bounds, of: view, preferredEdge: .minY)
        }
    }

    /// Prompt the user to save the study pack Markdown file to disk.
    @MainActor
    static func saveToDevice(_ analysis: MediaAnalysis) {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [UTType(filenameExtension: "md") ?? .plainText]
        panel.nameFieldStringValue = "\(fileBaseName(for: analysis)).md"
        panel.canCreateDirectories = true
        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }
            do {
                try markdown(for: analysis).write(to: url, atomically: true, encoding: .utf8)
            } catch {
                LogService.shared.error("Study pack export failed", error: error)
                let alert = NSAlert()
                alert.messageText = "Couldn't save study pack"
                alert.informativeText = error.localizedDescription
                alert.alertStyle = .warning
                alert.runModal()
            }
        }
    }

    /// Write the Markdown to a uniquely-named temp file for sharing.
    private static func writeTempFile(for analysis: MediaAnalysis) -> URL? {
        let dir = FileManager.default.temporaryDirectory
            .appendingPathComponent("StudyPackExports", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        let url = dir.appendingPathComponent("\(fileBaseName(for: analysis)).md")
        do {
            try markdown(for: analysis).write(to: url, atomically: true, encoding: .utf8)
            return url
        } catch {
            LogService.shared.error("Study pack share export failed", error: error)
            return nil
        }
    }

    // MARK: - Portable pack (.kekapack) encoding

    private static func packEncoder() -> JSONEncoder {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        return encoder
    }

    private static func packDecoder() -> JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return decoder
    }

    private static let manifestName = "manifest.json"

    /// Write a prepared pack to disk as an AppleArchive `.kekapack` container:
    /// stage `manifest.json` + the source directories, then archive the staging
    /// tree. The staging dir is always cleaned up.
    static func writePack(_ export: StudyPackExport, to destination: URL) throws {
        let fm = FileManager.default
        let staging = fm.temporaryDirectory
            .appendingPathComponent("kekapack-out-\(UUID().uuidString)", isDirectory: true)
        try fm.createDirectory(at: staging, withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: staging) }

        let manifest = try packEncoder().encode(export.bundle)
        try manifest.write(to: staging.appendingPathComponent(manifestName))

        for (archivePath, sourceURL) in export.fileSources {
            let dest = staging.appendingPathComponent(archivePath)
            try fm.createDirectory(at: dest.deletingLastPathComponent(), withIntermediateDirectories: true)
            try fm.copyItem(at: sourceURL, to: dest)
        }

        if fm.fileExists(atPath: destination.path) {
            try fm.removeItem(at: destination)
        }
        try StudyPackArchive.encode(directory: staging, to: destination)
    }

    /// Decode a `.kekapack` file. Format 2 is an AppleArchive (extracted to a
    /// temp dir the caller must clean up); format 1 is a single JSON file.
    /// Detected by the first byte: `{` ⇒ legacy JSON, otherwise archive.
    static func readPack(at url: URL) throws -> DecodedStudyPack {
        let handle = try FileHandle(forReadingFrom: url)
        let head = try handle.read(upToCount: 1)
        try? handle.close()

        if head?.first == 0x7B { // '{'  → legacy single-file JSON
            let bundle = try decodeManifest(Data(contentsOf: url))
            return DecodedStudyPack(bundle: bundle, rootDirectory: nil)
        }

        let extractDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("kekapack-in-\(UUID().uuidString)", isDirectory: true)
        try StudyPackArchive.decode(url, to: extractDir)
        let manifestURL = extractDir.appendingPathComponent(manifestName)
        let bundle = try decodeManifest(Data(contentsOf: manifestURL))
        return DecodedStudyPack(bundle: bundle, rootDirectory: extractDir)
    }

    private static func decodeManifest(_ data: Data) throws -> StudyPackBundle {
        let bundle = try packDecoder().decode(StudyPackBundle.self, from: data)
        guard bundle.formatVersion <= StudyPackBundle.currentFormatVersion else {
            throw StudyPackBundleError.unsupportedFormat(
                found: bundle.formatVersion,
                supported: StudyPackBundle.currentFormatVersion
            )
        }
        return bundle
    }

    // MARK: - Pack share / save

    /// Prompt the user to save a prepared pack as a portable `.kekapack` file.
    @MainActor
    static func savePackToDevice(_ export: StudyPackExport, suggestedName: String) {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.kekaPack]
        panel.nameFieldStringValue = "\(sanitizedBaseName(suggestedName)).kekapack"
        panel.canCreateDirectories = true
        panel.begin { response in
            guard response == .OK, let url = panel.url else { return }
            do {
                try writePack(export, to: url)
            } catch {
                presentError("Couldn't export study pack", error)
            }
        }
    }

    /// Prompt the user to pick `.kekapack` files and decode them. Returns the
    /// successfully decoded packs; surfaces a single alert for any failures.
    /// Callers must remove each `rootDirectory` once imported.
    @MainActor
    static func importPacksFromDisk() -> [DecodedStudyPack] {
        let panel = NSOpenPanel()
        panel.allowedContentTypes = [.kekaPack]
        panel.allowsMultipleSelection = true
        panel.canChooseDirectories = false
        panel.prompt = "Import"
        panel.message = "Choose one or more Kekasatori study packs (.kekapack)."
        guard panel.runModal() == .OK else { return [] }

        var packs: [DecodedStudyPack] = []
        var firstError: Error?
        for url in panel.urls {
            do {
                packs.append(try readPack(at: url))
            } catch {
                LogService.shared.error("Study pack import failed for \(url.lastPathComponent)", error: error)
                if firstError == nil { firstError = error }
            }
        }
        if let firstError, packs.isEmpty {
            presentError("Couldn't import study pack", firstError)
        }
        return packs
    }

    @MainActor
    private static func presentError(_ title: String, _ error: Error) {
        LogService.shared.error(title, error: error)
        let alert = NSAlert()
        alert.messageText = title
        alert.informativeText = error.localizedDescription
        alert.alertStyle = .warning
        alert.runModal()
    }
}
